### ISSUE TITLE
Hack And Chat March 2020

### ISSUE THREAD

**Issue by mre** [hello-rust/community#2]
Let's chat about Rust!
We don't really have an agenda yet, but we'll figure something out.
If you want to propose a talk, add a comment here. 😊 

* Date: 8th of March
* Time: 8pm (GMT+1)
* Location: https://gather.town/app/0Ez2adaJDhN67Xzw/rust
* Language: English

**Comment by mre** [comment]
Prepared some slides for [lychee](https://github.com/lycheeverse/lychee), a link checker written in Rust. If we find no other topics it might make for a nice conversation starter. 😉

**Comment by mre** [comment]
@hannobraun will give an introduction on the goals of an exciting new project called [flott](https://flott-motion.org/) &mdash; an ecosystem for motion control software in Rust. 🎉

**Comment by hendrikmaus** [comment]
I'll contribute a sneak peek into a new tool I've been working on. It's an attempt to simplify a gitops based build and delivery process based on github, google cloud build, argo-cd and kubernetes.

**Comment by mre** [comment]
See you tonight! https://everytimezone.com/s/ff05f8fd

**Comment by mre** [comment]
Thanks everyone for coming. ✌️😊
@hendrikmaus, @hannobraun: if you could upload the PDFs here that would be cool.

**Comment by hendrikmaus** [comment]
There is no material on my talk as of now.

**Comment by hannobraun** [comment]
My slides are pretty sparse and make little sense without the talk. Given that I'd have to put some more work into updating them before uploading (removing the copyrighted pictures), I wonder if that's worth the effort.

I'm happy to send them to anyone who wants them though. Just send me an email to hanno@braun-embedded.com.

**Comment by mre** [comment]
Cool, this is settled then. Thanks a lot for the talks. If anyone needs more info on the topics presented, don't hesitate to contact the speakers. 😊
